### ISSUE TITLE
scrooloose/syntastic 속도 문제

### ISSUE THREAD

**Issue by e-** [serendipitydeity/vimsettings#4]
C나 파이썬 등은 문법 체크가 빨라서 저장시 별 딜레이를 느끼지 못하는데 스칼라의 경우에는 너무 느려서 작업에 방해가 됩니다.

확장자를 보고 선별적으로 플러그인을 로드해야 할 것 같습니다.

**Comment by e-** [comment]
아니 관리자님 답변좀 해주시지요

**Comment by serendipitydeity** [comment]
컨트리뷰션 감사합니다
